/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tveqpmzgqtoyagtpapev"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2ZXFwbXpncXRveWFndHBhcGV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxNDk1NzMsImV4cCI6MjA3ODcyNTU3M30.Lk5-tJOzPp3cvqQjGcK6utBx69CcAla2AKyBmqFPlm0"
